In [1]:
x = [1,2]
y = [3,4]
x+y

[1, 2, 3, 4]

In [9]:
import numpy as np

In [11]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [14]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print('x='+str(x))
print('y='+str(y))
z =x+y
print('x+y='+str(z))

x=[1 2 3]
y=[4 5 6]
x+y=[5 7 9]


In [15]:
type(z)

numpy.ndarray

In [22]:
import numpy as np
x = np.array([1,2,3])
print(x)

x[0] = 100
print(x)

[1 2 3]
[100   2   3]


In [23]:
y = np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
y = np.arange(5,15)
print(y)

[ 5  6  7  8  9 10 11 12 13 14]


In [29]:
a = np.array([1,2,3,4,5])
b = a
print('a='+str(a)+'b='+str(b))

a[0] = 100

print('a='+str(a)+'b='+str(b))

a=[1 2 3 4 5]b=[1 2 3 4 5]
a=[100   2   3   4   5]b=[100   2   3   4   5]


In [30]:
a = np.array([1,2,3,4,5])
b = a.copy()
print('a='+str(a)+'b='+str(b))

a[0] = 100

print('a='+str(a)+'b='+str(b))

a=[1 2 3 4 5]b=[1 2 3 4 5]
a=[100   2   3   4   5]b=[1 2 3 4 5]


In [32]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [34]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
x.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [35]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

w,h = x.shape
print(w)
print(h)

[[1 2 3]
 [4 5 6]]
2
3


In [36]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x[0,0])
print(x[1,1])
x[0,0] =100

print(x)

[[1 2 3]
 [4 5 6]]
1
5
[[100   2   3]
 [  4   5   6]]


In [37]:
x = np.zeros(2)
print(x)

[0. 0.]


In [38]:
y= np.zeros((2,2))
print(y)

[[0. 0.]
 [0. 0.]]


In [40]:
z= np.zeros((2,2,2))
print(z)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [41]:
y= np.ones(2)
print(y)

[1. 1.]


In [43]:
y= np.ones((2,2))
print(y)

[[1. 1.]
 [1. 1.]]


In [45]:
x = np.random.rand(5)
print(x)

[0.68902558 0.16972194 0.32652931 0.19526197 0.59394856]


In [46]:
y = np.random.rand(5,2)
print(y)

[[0.83191222 0.23803   ]
 [0.62816533 0.3131841 ]
 [0.70995247 0.38065988]
 [0.51865708 0.53948556]
 [0.71312349 0.23719388]]


In [47]:
a =np.array([1,2,3,4])
print(a)

b= a.reshape(2,2)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]]
