In [8]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

data = np.loadtxt(fname = "Breast_cancer_data.txt")

X = data[:,:9]
T = data[:,9]
X = X.astype(int)
T = T.astype(int)

X_n = data.shape[0]

print(X_n)
print(X)
print(T)
T = np.abs((1-T))
print(T)
# print(X[1,2])

683
[[ 5 10  6 ...  4 10 10]
 [ 3  1  1 ...  1  1  1]
 [ 3  1  2 ...  2  1  1]
 ...
 [ 3  1  1 ...  1  1  1]
 [ 3  1  1 ...  1  1  1]
 [ 5  1  1 ...  3  1  1]]
[1 0 0 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0
 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0
 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 1 0
 1 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0
 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0
 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1
 0 1 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 1 1 1 0
 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 1 0 0 1 1
 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 1 0 1 0 0 0 1 1 0 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1
 1 1 0 0 0 1 0 

In [12]:
def logistic2(x0,x1,x2,x3,x4,x5,x6,x7,x8,w):
    y = 1/(1 + np.exp(-(w[0]*x0 + w[1]*x1 + w[2]*x2 + w[3]*x3 + w[4]*x4 + w[5]*x5 + w[6]*x6 + w[7]*x7 + w[8]*x8 + w[9])))
    return y

from mpl_toolkits.mplot3d import axes3d


In [13]:
def cee_logistic2(w,x,t):
    X_n = x.shape[0]
    y = logistic2(x[:,0],x[:,1],x[:,2],x[:,3],x[:,4],x[:,5],x[:,6],x[:,7],x[:,8],w)
    cee=0 
    for n in range(len(y)):
        cee = cee - (t[n] * np.log(y[n]) + (1-t[n]) * np.log(1-y[n]))
    cee = cee/X_n
    
    return cee

def dcee_logistic2(w,x,t):
    X_n = x.shape[0]
    y = logistic2(x[:,0],x[:,1],x[:,2],x[:,3],x[:,4],x[:,5],x[:,6],x[:,7],x[:,8],w)
    dcee = np.zeros(10)
    for n in range(len(y)):
        dcee[0] = dcee[0]+(y[n]-t[n])*x[n,0]
        dcee[1] = dcee[1]+(y[n]-t[n])*x[n,1]
        dcee[2] = dcee[2]+(y[n]-t[n])*x[n,2]
        dcee[3] = dcee[3]+(y[n]-t[n])*x[n,3]
        dcee[4] = dcee[4]+(y[n]-t[n])*x[n,4]
        dcee[5] = dcee[5]+(y[n]-t[n])*x[n,5]
        dcee[6] = dcee[6]+(y[n]-t[n])*x[n,6]
        dcee[7] = dcee[7]+(y[n]-t[n])*x[n,7]
        dcee[8] = dcee[8]+(y[n]-t[n])*x[n,8]
        dcee[9] = dcee[9]+(y[n]-t[n])
    dcee = dcee/X_n
    return dcee

W = [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]
# cee_logistic2(W,X,T)
dcee_logistic2(W,X,T)

array([-1.92679126, -0.84919291, -0.91947105, -0.87554719, -1.37042153,
       -0.87554722, -1.35431661, -0.81991032, -0.69253114, -0.6500714 ])

In [14]:
def kfold_logistic2_func(x,t,w_init,k):
    n = x.shape[0]
    cee_train = np.zeros(k)
    cee_test = np.zeros(k)
    
    
    for i in range(0,k):
        x_train = x[np.fmod(range(n),k) != i]
        t_train = t[np.fmod(range(n),k) != i]
        x_test = x[np.fmod(range(n),k) == i]
        t_test = t[np.fmod(range(n),k) == i]
        W = fit_logistic2(w_init, x_train, t_train)
        cee_train[i] = cee_logistic2(W,x_train, t_train)
        cee_test[i]  = cee_logistic2(W,x_test, t_test)
        print("w0 = {0:.2f}, w1={1:.2f}, w2={2:.2f}, w3 = {3:.2f}, w4={4:.2f}, w5={5:.2f}, w6 = {6:.2f}, w7={7:.2f},w8={8:.2f}, w9={9:.2f}"
      .format(W[0],W[1],W[2],W[3],W[4],W[5],W[6],W[7],W[8],W[9]))
        print("CEE_train = {0:.2f}, CEE_test = {1:.2f}".format(cee_train[i], cee_test[i]))
        
    return cee_train, cee_test

In [15]:
from scipy.optimize import minimize

def fit_logistic2(w_init,x,t):
    res = minimize(cee_logistic2, w_init, args = (x,t),
                  jac=dcee_logistic2, method="CG")
    return res.x

K = 10
W_Kfold = np.zeros(K)

W_init = [0,0,0,0,0,0,0,0,0,0]
# W = fit_logistic2(W_init, X, T)
kfold_logistic2_func(X,T,W_init,K)
# for i in range()
# print("w0 = {0:.2f}, w1={1:.2f}, w2={2:.2f}, w3 = {3:.2f}, w4={4:.2f}, w5={5:.2f}, w6 = {6:.2f}, w7={7:.2f}, w8={8:.2f}, w9={9:.2f}"
#       .format(W[0],W[1],W[2],W[3],W[4],W[5],W[6],W[7],W[8],W[9]))

# cee = cee_logistic2(W, X, T)
# print(X, T)
# print("CEE = {0:.2f}".format(cee))

w0 = -0.53, w1=0.11, w2=-0.38, w3 = -0.38, w4=-0.15, w5=-0.43, w6 = -0.35, w7=-0.27, w8=-0.57, w9=10.27
CEE_train = 0.07, CEE_test = 0.11
w0 = -0.58, w1=-0.19, w2=-0.25, w3 = -0.34, w4=-0.10, w5=-0.38, w6 = -0.49, w7=-0.08, w8=-0.43, w9=10.32
CEE_train = 0.07, CEE_test = 0.13
w0 = -0.57, w1=0.10, w2=-0.40, w3 = -0.40, w4=-0.19, w5=-0.36, w6 = -0.44, w7=-0.17, w8=-0.56, w9=10.61
CEE_train = 0.07, CEE_test = 0.12
w0 = -0.53, w1=0.03, w2=-0.29, w3 = -0.33, w4=-0.11, w5=-0.36, w6 = -0.44, w7=-0.25, w8=-0.54, w9=9.98
CEE_train = 0.08, CEE_test = 0.04
w0 = -0.64, w1=0.07, w2=-0.25, w3 = -0.33, w4=-0.08, w5=-0.41, w6 = -0.57, w7=-0.28, w8=-0.64, w9=10.99
CEE_train = 0.07, CEE_test = 0.13
w0 = -0.44, w1=-0.18, w2=-0.46, w3 = -0.14, w4=-0.03, w5=-0.40, w6 = -0.35, w7=-0.24, w8=-0.42, w9=9.48
CEE_train = 0.07, CEE_test = 0.14
w0 = -0.51, w1=-0.03, w2=-0.27, w3 = -0.31, w4=-0.07, w5=-0.39, w6 = -0.44, w7=-0.21, w8=-0.54, w9=9.76
CEE_train = 0.08, CEE_test = 0.02
w0 = -0.53, w1=-0.01, w2=-0.29, w3

(array([0.07269322, 0.07129412, 0.07082762, 0.07993577, 0.07060801,
        0.07234716, 0.0819383 , 0.08189511, 0.06662865, 0.07596151]),
 array([0.10800198, 0.12870526, 0.12436363, 0.0362698 , 0.12898861,
        0.13799697, 0.0168025 , 0.01706208, 0.16116058, 0.08355489]))

In [17]:
def validate_model(w):
    d = np.loadtxt(fname = "Sample_test_data.txt")
    X = d[:,:9].astype(int)
    T = d[:,9].astype(int)
    
    N = X.shape[0]
    
    y = np.zeros(N)
    err_cnt = 0
    decision = np.zeros(N).astype(int)
    
    print('No. \t Y \t T')
    print('---------------------')
    for i in range(N):
        x = np.r_[X[i,:],1]
        u = np.array(w).dot(x)
        y[i] = 1 / (1 + np.exp(-u))
        if y[i] < 0.5:
            decision[i] = 1
        
        if decision[i] != T[i] :
            err_cnt = err_cnt + 1
        
        print('{0} \t {1} \t {2}'.format(i, decision[i], T[i]))
        print(y[i])
        
    hit_ratio = np.round((1-err_cnt/N)*100,1)
    
    print('---------------------')
    print('Total error : {0} out of {1}'.format(err_cnt, N))
    print('Hit ratio   : {0:.1f}%'.format(hit_ratio))
    
    return hit_ratio

StudentID = "2016142020"
W = np.loadtxt(fname = StudentID+".txt")

print("Student ID : "+StudentID)
print("W = "+np.str(W))
print("\n")
validate_model(W)

Student ID : 2016142020
W = [-0.53  0.01 -0.29 -0.33 -0.1  -0.37 -0.42 -0.21 -0.56  9.85]


No. 	 Y 	 T
---------------------
0 	 0 	 0
0.9983739919733222
1 	 0 	 0
0.968629067751806
2 	 0 	 0
0.9975273768433653
3 	 1 	 1
0.00028012344899482766
4 	 0 	 0
0.9667536911605259
5 	 0 	 0
0.9990422829475397
6 	 1 	 1
0.0003632703132180771
7 	 0 	 0
0.9990422829475397
8 	 1 	 1
0.00599986722748388
9 	 1 	 1
0.012493186263129532
10 	 0 	 0
0.9906223111373232
11 	 1 	 1
0.0034019457029172617
12 	 1 	 1
0.000525833480796639
13 	 0 	 0
0.9945137011005495
14 	 0 	 0
0.998148673818794
15 	 1 	 1
0.00011505329986124895
16 	 0 	 0
0.9977843691081794
17 	 0 	 0
0.9879907956900725
18 	 1 	 1
0.003368209791246832
19 	 0 	 0
0.9847828787913436
20 	 0 	 0
0.992076757875765
21 	 1 	 1
0.3273929829322396
22 	 0 	 0
0.9936314844931844
23 	 0 	 0
0.9985284994026105
24 	 0 	 1
0.6058736684317605
25 	 1 	 1
0.011430203126470714
26 	 1 	 1
0.13943387296164983
27 	 1 	 1
0.3186462662109745
28 	 1 	 1
3.9278620026

98.4